### PR TITLE
Filling out outline

### PR DESCRIPTION
**Pull request by kball**
Restructure outline to have subheadings and start filling out content for sections 2, 3, and 5.

### CODE REVIEW

**Comment by treyhunner** [comment]
It would be nice to move some of this into the [workshop.md](https://github.com/sandiego-ember/ember-cli-101/blob/master/workshop.md) file eventually.

**Comment by kball** [comment]
@treyhunner which parts would you like in workshop.md vs the outline?  I thought you had mentioned maybe putting it all in one big file?

**Comment by treyhunner** [comment]
I copied the stuff in outline from a Google doc we were originally using. By the time of the workshop all instructions will be in workshop.md and outline.md will be deleted.

Don't worry about where you put it all for now. I'll end up moving it all to workshop.md.

**Comment by hbrysiewicz** [comment]
+1 for the merge please

**Pull request merged**
